services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: goalbet
      POSTGRES_PASSWORD: goalbet
      POSTGRES_DB: goalbet
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U goalbet" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped



volumes:
  pg_data: